name: Build and deploy docker image

on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'           # Push events to every tag not containing /

jobs:

  build:
    # Run build on our self-hosted runner, we had trouble with shared runners
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Get current tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Build the Docker image
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        # Create build container
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use

        # Authenticate on registries
        docker login --username ${{ secrets.DOCKERLOGIN }} --password ${{ secrets.DOCKERPWD }}
        docker login https://docker.pkg.github.com -u qdrant --password ${{ secrets.GITHUB_TOKEN }}

        # Build regular image for Docker Hub
        # DOCKERHUB_TAG="aletheiaai/deployments:qdrant.${{ github.ref_name }}"
        DOCKERHUB_TAG="aletheiaai/deployments:qdrant.main"
        TAGS="-t ${DOCKERHUB_TAG}"

        # Pull, retag and push to GitHub packages
        docker buildx build --platform='linux/amd64,linux/arm64' $TAGS --push .